name = "authentication-dev"
type = "javascript"
account_id = "41d154df19739a540756d193a9715370"
zone_id = "b871929efc74ff6123beaff3a5f55841"
workers_dev = true
vars = { ENVIRONMENT = "development", SENTRY_DSN = "", GITHUB_CLIENT_ID = "6eb5a1498759538f2d8c", GITHUB_CLIENT_SECRET = "" }

[build]
command = "npm install && npm run build"
upload.format = "service-worker"

[env.production]
name = "authentication"
route = "https://glenstack.dev/login*"
vars = { ENVIRONMENT = "production", GITHUB_CLIENT_ID = "6eb5a1498759538f2d8c" }