name = "api"
type = "webpack"
webpack_config = "./webpack.config.js"
account_id = "41d154df19739a540756d193a9715370"
zone_id = "b871929efc74ff6123beaff3a5f55841"
route = "https://glenstack.dev/graphql*"
