name = "api-dev"
type = "javascript"
account_id = "41d154df19739a540756d193a9715370"
zone_id = "b871929efc74ff6123beaff3a5f55841"
workers_dev = true
vars = { ENVIRONMENT = "development", FAUNA_ADMIN_KEY = "", SENTRY_DSN = "" }

[build]
command = "npm install && npm run build"
upload.format = "service-worker"

[env.production]
name = "api"
route = "https://glenstack.dev/graphql*"
vars = { ENVIRONMENT = "production" }