name = "api-dev"
main = "dist/worker.js"
account_id = "41d154df19739a540756d193a9715370"
zone_id = "1a50aad2a97cd8ee713df553f2214779"
workers_dev = true
vars = { ENVIRONMENT = "development", FAUNA_ADMIN_KEY = "", SENTRY_DSN = "", IUBENDA_ID = "15821943" }

[build]
command = "npm install && npm run build"
upload.format = "service-worker"

[env.production]
name = "api"
route = "https://api.glenstack.com/*"
vars = { ENVIRONMENT = "production", IUBENDA_ID = "15821943" }