name = "upload-dev"
main = "dist/worker.js"
account_id = "41d154df19739a540756d193a9715370"
zone_id = "1a50aad2a97cd8ee713df553f2214779"
usage_model = "unbound"
workers_dev = true
vars = { ENVIRONMENT = "development", SENTRY_DSN = "" }
kv_namespaces = [
	 { binding = "FILES", id = "7b125cb0163343bd80a4eae98b1d1d96", preview_id = "7b125cb0163343bd80a4eae98b1d1d96" }
]

[build]
command = "npm install && npm run build"
upload.format = "service-worker"

[env.production]
name = "upload"
route = "https://upload.glenstack.com/*"
vars = { ENVIRONMENT = "production" }
kv_namespaces = [
	 { binding = "FILES", id = "7b125cb0163343bd80a4eae98b1d1d96", preview_id = "7b125cb0163343bd80a4eae98b1d1d96" }
]
