name: Test
on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    name: Test
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Read .nvmrc
        run: echo ::set-output name=NVMRC::$(cat .nvmrc)
        id: nvm
      - name: Setup node
        uses: actions/setup-node@v2
        with:
          node-version: "${{ steps.nvm.outputs.NVMRC }}"
      - name: Install Doppler
        run: (curl -Ls https://cli.doppler.com/install.sh || wget -qO- https://cli.doppler.com/install.sh) | sudo sh
      - name: Install
        run: npm ci
      - name: Test & publish code coverage
        uses: paambaati/codeclimate-action@v2.7.5
        env:
          CC_TEST_REPORTER_ID: "${{ secrets.CC_TEST_REPORTER_ID }}"
        with:
          coverageCommand: npm run validate
          coverageLocations: |
            ${{github.workspace}}/packages/api/coverage/lcov.info:lcov
            ${{github.workspace}}/packages/upload/coverage/lcov.info:lcov
            ${{github.workspace}}/packages/status/coverage/lcov.info:lcov
            ${{github.workspace}}/packages/authentication/coverage/lcov.info:lcov
            ${{github.workspace}}/packages/glenstack.com/coverage/lcov.info:lcov
            ${{github.workspace}}/packages/glenstack.com/workers-site/coverage/lcov.info:lcov
